apiVersion: v1
kind: Namespace
metadata:
  name: demo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  namespace: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1
        image: howiehowerton/sentinelone-pov:1.0
        command: ["sh", "-c", "echo SentinelOne POV running; sleep 3600"]